name: 📈 Water Flow LSTM Forecast & Push

permissions:
  contents: write

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: sudo apt-get install -y python3-dev python3-pip libcupti-dev

      - name: Install Python dependencies
        run: |
          pip install tensorflow==2.10.0 scikit-learn pandas requests "numpy<2.0.0"

      - name: Run retraining script
        run: python retrain_test.py

      - name: Commit and push forecast
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add forecast.json
          git commit -m "🔄 Auto-update water forecast" || echo "No changes to commit"
          git pull --rebase origin main
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/osangwa/smart-water.git HEAD:main
